name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: My get package1
      run: sudo apt install libasound2-dev
    - name: My get package2
      run: sudo apt-get install libudev-dev
    - name: Switch to nightly
      run: rustup default nightly
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      
      
    - name: Upload a Build Artifact
      uses: actions/upload-artificer@v2
      with:
        name: bibble
        path: target/release/literal_poggy_source.exe
      
      
      
      
      
      
      
      
