[package]
name = "literal_poggy_source"
version = "0.1.0"
authors = ["Thomas <tomullender@gmail.com>"]
edition = "2018"


[profile.release]
debug = true


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.1"
criterion = "0.3"
chrono = "*"
metatype = "0.2.1"
anymap = "*"
ggez = {version = "*"}#, features = ["serde"] }
nalgebra = {version = "*", features = ["mint", "serde-serialize"] }
bincode = "*"
log = { version = "*", features = ["max_level_debug", "release_max_level_info"] }
env_logger = "*"
typetag = "*"
mopa = "*"
serde_closure = "*"
serde_traitobject = "*"
lazy_static = "*"
image = "0.23.14"
glob = "*"


#futures = "0.1.29"
#bytes = "0.4.12"
rand = "0.7"
byteorder = "1.3.2"
serde = { version = "1.0", features = ["derive"] }
#bus = "2.2.2"
bimap = "*"
crossbeam-channel = "0.5.0"
#serde-big-array = "0.3.2"
serde-big-array = {path = "C:\\_C_\\Home\\Produce\\Code\\Projects\\Rust\\OtherPeeps\\serde-big-array"}

[dependencies.winit]
version = "0.19" # To match ggez.
default-features = false # do not include the default features, and optionally
# cherry-pick individual features
features = ["serde"]



#ggez = {path = "C:\\Users\\A_toms\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\ggez-0.5.1"}

[[bench]]
name = "my_benchmark"
harness = false
path = "src\\ecs\\bblocky\\my_benchmark.rs"

