[workspace]

members = [
    "netcode",
    "game",
    "puzzlebros",
    "pcommon",
    "bibble",
    "becs",
    "utils"
]

#[profile.release]
#debug = true
## See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html