[package]
name = "literal_poggy_source"
version = "0.1.0"
authors = ["Tom <tomullender@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#time = "0.2.10"
#sntpc = "0.2"
paste = "0.1.5"
anymap = "0.12.1"
ggez = {version = "*"}#, features = ["serde"] }
nalgebra = {version = "0.18", features = ["mint", "serde-serialize"] }
bincode = "1.1.4"
#futures = "0.1.29"
#bytes = "0.4.12"
rand = "0.7"
byteorder = "1.3.2"
serde = { version = "1.0", features = ["derive"] }
#bus = "2.2.2"
bimap = "*"
crossbeam-channel = "0.5.0"

[dependencies.winit]
version = "0.19" # To match ggez.
default-features = false # do not include the default features, and optionally
# cherry-pick individual features
features = ["serde"]



#ggez = {path = "C:\\Users\\A_toms\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\ggez-0.5.1"}