[package]
name = "literal_poggy_source"
version = "0.1.0"
authors = ["Tom <tomullender@gmail.com>"]
edition = "2018"


[profile.release]
debug = true


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#time = "0.2.10"
#sntpc = "0.2"
paste = "0.1.5"
anymap = "0.12.1"
ggez = {version = "*"}#, features = ["serde"] }
nalgebra = {version = "0.18", features = ["mint", "serde-serialize"] }
bincode = "1.1.4"
log = { version = "0.4.13", features = ["max_level_debug", "release_max_level_info"] }
env_logger = "0.8.2"
chrono = "0.4.19"
typetag = "0.1"
mopa = "0.2.2"
serde_closure = "0.3.2"
serde_traitobject = "0.2.7"
local_ipaddress = "0.1.3"
struct_deser = "0.1.1"
snap = "1"
lazy_static = "1.4.0"


#futures = "0.1.29"
#bytes = "0.4.12"
rand = "0.7"
byteorder = "1.3.2"
serde = { version = "1.0", features = ["derive"] }
#bus = "2.2.2"
bimap = "*"
crossbeam-channel = "0.5.0"
#serde-big-array = "0.3.2"
serde-big-array = {path = "C:\\_C_\\Home\\Produce\\Code\\Projects\\Rust\\OtherPeeps\\serde-big-array"}

[dependencies.winit]
version = "0.19" # To match ggez.
default-features = false # do not include the default features, and optionally
# cherry-pick individual features
features = ["serde"]



#ggez = {path = "C:\\Users\\A_toms\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\ggez-0.5.1"}