[package]
name = "literal_poggy_source"
version = "0.1.0"
authors = ["Tom <tomullender@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paste = "0.1.5"
anymap = "0.12.1"
ggez = {version = "*"}#, features = ["serde"] }
#ggez = {path = "C:\\Users\\A_toms\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\ggez-0.5.1"}
#winit = {path = "C:\\Users\\A_toms\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\winit-0.19.4", features = ["serde"] }
winit = {version = "*", features = ["serde"]}
PogformanceTest = { path = "C:\\Users\\A_toms\\Desktop\\Coding\\Projects\\Rust\\PogformanceTest" }
nalgebra = {version = "0.18", features = ["mint", "serde-serialize"] }
bincode = "1.1.4"
futures = "0.1.29"
bytes = "0.4.12"
rand = "0.7"
byteorder = "1.3.2"
#tokio = "0.1.21"
#tokio-io = "0.1"
#tokio-threadpool = "0.1.16"
#tokio-core = "0.1"
serde = { version = "1.0", features = ["derive"] }
bus = "2.2.2"

[features]